# frozen_string_literal: true

ENV['COCOAPODS_DISABLE_STATS'] = '1'

source 'https://github.com/CocoaPods/Specs.git'

plugin 'cocoapods-bazel'

use_frameworks!

install! 'cocoapods',
         integrate_targets: false

all_podspecs = Dir['**/*.podspec', base: __dir__] - %w[Frameworks/e/E.podspec]

target 'App' do
  platform :ios, '9.0'

  all_podspecs.each do |podspec|
    spec = Pod::Specification.from_file(File.join(__dir__, podspec))
    subspecs = spec.recursive_subspecs.group_by(&:spec_type)
    pod spec.name, path: podspec, testspecs: Array(subspecs[:test]).map(&:base_name), appspecs: Array(subspecs[:app]).map(&:base_name)
  end

  target 'AppTests' do
    inherit! :search_paths

    pod 'E', path: 'Frameworks/e/E.podspec', testspecs: %w[Tests]
  end
end
